---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "0778ca6a-6a9a-11ef-b561-aeb7f1c0facf",
        "monitors": [
          "10.31.0.77:6789",
          "10.31.0.78:6789",
          "10.31.0.79:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph-csi
