apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  ports:
  - name: web-ui
    protocol: TCP
    port: 3001
    targetPort: 3001
  clusterIP: None
  selector:
    app: uptime-kuma
